/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserProfileModel } from '../../models/user-profile-model';

export interface GetUserProfileById$Params {
  id?: string;
}

export function getUserProfileById(http: HttpClient, rootUrl: string, params?: GetUserProfileById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileModel>> {
  const rb = new RequestBuilder(rootUrl, getUserProfileById.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserProfileModel>;
    })
  );
}

getUserProfileById.PATH = '/api/users/get';
