/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderModel } from '../../models/order-model';

export interface GetCustomerOrders$Params {
  customerId?: string;
}

export function getCustomerOrders(http: HttpClient, rootUrl: string, params?: GetCustomerOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderModel>>> {
  const rb = new RequestBuilder(rootUrl, getCustomerOrders.PATH, 'get');
  if (params) {
    rb.query('customerId', params.customerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderModel>>;
    })
  );
}

getCustomerOrders.PATH = '/api/orders/get-all-by-customer';
