/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderModel } from '../../models/order-model';

export interface GetOrder$Params {
  id?: string;
}

export function getOrder(http: HttpClient, rootUrl: string, params?: GetOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderModel>> {
  const rb = new RequestBuilder(rootUrl, getOrder.PATH, 'get');
  if (params) {
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderModel>;
    })
  );
}

getOrder.PATH = '/api/orders/get';
