/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OfferModel } from '../../models/offer-model';

export interface GetOffersByOrder$Params {
  orderId?: string;
}

export function getOffersByOrder(http: HttpClient, rootUrl: string, params?: GetOffersByOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OfferModel>>> {
  const rb = new RequestBuilder(rootUrl, getOffersByOrder.PATH, 'get');
  if (params) {
    rb.query('orderId', params.orderId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OfferModel>>;
    })
  );
}

getOffersByOrder.PATH = '/api/offers/get-all-by-order';
