/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addOffer } from '../fn/offers/add-offer';
import { AddOffer$Params } from '../fn/offers/add-offer';
import { deleteOffer } from '../fn/offers/delete-offer';
import { DeleteOffer$Params } from '../fn/offers/delete-offer';
import { getOffer } from '../fn/offers/get-offer';
import { GetOffer$Params } from '../fn/offers/get-offer';
import { getOffersByCarrier } from '../fn/offers/get-offers-by-carrier';
import { GetOffersByCarrier$Params } from '../fn/offers/get-offers-by-carrier';
import { getOffersByOrder } from '../fn/offers/get-offers-by-order';
import { GetOffersByOrder$Params } from '../fn/offers/get-offers-by-order';
import { OfferModel } from '../models/offer-model';
import { updateOffer } from '../fn/offers/update-offer';
import { UpdateOffer$Params } from '../fn/offers/update-offer';

@Injectable({ providedIn: 'root' })
export class OffersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `addOffer()` */
  static readonly AddOfferPath = '/api/offers/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addOffer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addOffer$Response(params?: AddOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addOffer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addOffer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addOffer(params?: AddOffer$Params, context?: HttpContext): Observable<void> {
    return this.addOffer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateOffer()` */
  static readonly UpdateOfferPath = '/api/offers/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOffer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOffer$Response(params?: UpdateOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateOffer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOffer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOffer(params?: UpdateOffer$Params, context?: HttpContext): Observable<void> {
    return this.updateOffer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteOffer()` */
  static readonly DeleteOfferPath = '/api/offers/delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOffer()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOffer$Response(params?: DeleteOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteOffer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOffer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOffer(params?: DeleteOffer$Params, context?: HttpContext): Observable<void> {
    return this.deleteOffer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getOffer()` */
  static readonly GetOfferPath = '/api/offers/get';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOffer()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffer$Response(params?: GetOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferModel>> {
    return getOffer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOffer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffer(params?: GetOffer$Params, context?: HttpContext): Observable<OfferModel> {
    return this.getOffer$Response(params, context).pipe(
      map((r: StrictHttpResponse<OfferModel>): OfferModel => r.body)
    );
  }

  /** Path part for operation `getOffersByOrder()` */
  static readonly GetOffersByOrderPath = '/api/offers/get-all-by-order';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOffersByOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffersByOrder$Response(params?: GetOffersByOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OfferModel>>> {
    return getOffersByOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOffersByOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffersByOrder(params?: GetOffersByOrder$Params, context?: HttpContext): Observable<Array<OfferModel>> {
    return this.getOffersByOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OfferModel>>): Array<OfferModel> => r.body)
    );
  }

  /** Path part for operation `getOffersByCarrier()` */
  static readonly GetOffersByCarrierPath = '/api/offers/get-all-by-carrier';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOffersByCarrier()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffersByCarrier$Response(params?: GetOffersByCarrier$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OfferModel>>> {
    return getOffersByCarrier(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOffersByCarrier$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffersByCarrier(params?: GetOffersByCarrier$Params, context?: HttpContext): Observable<Array<OfferModel>> {
    return this.getOffersByCarrier$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OfferModel>>): Array<OfferModel> => r.body)
    );
  }

}
