/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addOrder } from '../fn/orders/add-order';
import { AddOrder$Params } from '../fn/orders/add-order';
import { deleteOrder } from '../fn/orders/delete-order';
import { DeleteOrder$Params } from '../fn/orders/delete-order';
import { getCustomerOrders } from '../fn/orders/get-customer-orders';
import { GetCustomerOrders$Params } from '../fn/orders/get-customer-orders';
import { getOrder } from '../fn/orders/get-order';
import { GetOrder$Params } from '../fn/orders/get-order';
import { getOrders } from '../fn/orders/get-orders';
import { GetOrders$Params } from '../fn/orders/get-orders';
import { OrderModel } from '../models/order-model';
import { updateOrder } from '../fn/orders/update-order';
import { UpdateOrder$Params } from '../fn/orders/update-order';

@Injectable({ providedIn: 'root' })
export class OrdersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCustomerOrders()` */
  static readonly GetCustomerOrdersPath = '/api/orders/get-all-by-customer';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCustomerOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomerOrders$Response(params?: GetCustomerOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderModel>>> {
    return getCustomerOrders(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCustomerOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomerOrders(params?: GetCustomerOrders$Params, context?: HttpContext): Observable<Array<OrderModel>> {
    return this.getCustomerOrders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OrderModel>>): Array<OrderModel> => r.body)
    );
  }

  /** Path part for operation `getOrders()` */
  static readonly GetOrdersPath = '/api/orders/get-all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrders$Response(params?: GetOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderModel>>> {
    return getOrders(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrders(params?: GetOrders$Params, context?: HttpContext): Observable<Array<OrderModel>> {
    return this.getOrders$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OrderModel>>): Array<OrderModel> => r.body)
    );
  }

  /** Path part for operation `getOrder()` */
  static readonly GetOrderPath = '/api/orders/get';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrder$Response(params?: GetOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderModel>> {
    return getOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrder(params?: GetOrder$Params, context?: HttpContext): Observable<OrderModel> {
    return this.getOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderModel>): OrderModel => r.body)
    );
  }

  /** Path part for operation `addOrder()` */
  static readonly AddOrderPath = '/api/orders/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addOrder$Response(params?: AddOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addOrder(params?: AddOrder$Params, context?: HttpContext): Observable<void> {
    return this.addOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateOrder()` */
  static readonly UpdateOrderPath = '/api/orders/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOrder$Response(params?: UpdateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOrder(params?: UpdateOrder$Params, context?: HttpContext): Observable<void> {
    return this.updateOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteOrder()` */
  static readonly DeleteOrderPath = '/api/orders/delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOrder()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOrder$Response(params?: DeleteOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOrder$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOrder(params?: DeleteOrder$Params, context?: HttpContext): Observable<void> {
    return this.deleteOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
