/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addTransport } from '../fn/transports/add-transport';
import { AddTransport$Params } from '../fn/transports/add-transport';
import { deleteTransport } from '../fn/transports/delete-transport';
import { DeleteTransport$Params } from '../fn/transports/delete-transport';
import { getTransport } from '../fn/transports/get-transport';
import { GetTransport$Params } from '../fn/transports/get-transport';
import { getTransportsByCarrier } from '../fn/transports/get-transports-by-carrier';
import { GetTransportsByCarrier$Params } from '../fn/transports/get-transports-by-carrier';
import { TransportModel } from '../models/transport-model';
import { updateTransport } from '../fn/transports/update-transport';
import { UpdateTransport$Params } from '../fn/transports/update-transport';

@Injectable({ providedIn: 'root' })
export class TransportsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTransportsByCarrier()` */
  static readonly GetTransportsByCarrierPath = '/api/transports/get-all-by-carrier';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransportsByCarrier()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransportsByCarrier$Response(params?: GetTransportsByCarrier$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportModel>>> {
    return getTransportsByCarrier(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransportsByCarrier$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransportsByCarrier(params?: GetTransportsByCarrier$Params, context?: HttpContext): Observable<Array<TransportModel>> {
    return this.getTransportsByCarrier$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<TransportModel>>): Array<TransportModel> => r.body)
    );
  }

  /** Path part for operation `getTransport()` */
  static readonly GetTransportPath = '/api/transports/get';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransport()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransport$Response(params?: GetTransport$Params, context?: HttpContext): Observable<StrictHttpResponse<TransportModel>> {
    return getTransport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransport(params?: GetTransport$Params, context?: HttpContext): Observable<TransportModel> {
    return this.getTransport$Response(params, context).pipe(
      map((r: StrictHttpResponse<TransportModel>): TransportModel => r.body)
    );
  }

  /** Path part for operation `addTransport()` */
  static readonly AddTransportPath = '/api/transports/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addTransport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addTransport$Response(params?: AddTransport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return addTransport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addTransport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addTransport(params?: AddTransport$Params, context?: HttpContext): Observable<void> {
    return this.addTransport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateTransport()` */
  static readonly UpdateTransportPath = '/api/transports/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTransport()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTransport$Response(params?: UpdateTransport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateTransport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTransport$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTransport(params?: UpdateTransport$Params, context?: HttpContext): Observable<void> {
    return this.updateTransport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteTransport()` */
  static readonly DeleteTransportPath = '/api/transports/delete';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTransport()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTransport$Response(params?: DeleteTransport$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTransport(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTransport$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTransport(params?: DeleteTransport$Params, context?: HttpContext): Observable<void> {
    return this.deleteTransport$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
