/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getUserProfileById } from '../fn/users/get-user-profile-by-id';
import { GetUserProfileById$Params } from '../fn/users/get-user-profile-by-id';
import { register } from '../fn/users/register';
import { Register$Params } from '../fn/users/register';
import { updateUserProfile } from '../fn/users/update-user-profile';
import { UpdateUserProfile$Params } from '../fn/users/update-user-profile';
import { UserProfileModel } from '../models/user-profile-model';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `register()` */
  static readonly RegisterPath = '/api/users/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register$Response(params?: Register$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return register(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register(params?: Register$Params, context?: HttpContext): Observable<void> {
    return this.register$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `updateUserProfile()` */
  static readonly UpdateUserProfilePath = '/api/users/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUserProfile()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserProfile$Response(params?: UpdateUserProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return updateUserProfile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUserProfile$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUserProfile(params?: UpdateUserProfile$Params, context?: HttpContext): Observable<void> {
    return this.updateUserProfile$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getUserProfileById()` */
  static readonly GetUserProfileByIdPath = '/api/users/get';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserProfileById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserProfileById$Response(params?: GetUserProfileById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileModel>> {
    return getUserProfileById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserProfileById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserProfileById(params?: GetUserProfileById$Params, context?: HttpContext): Observable<UserProfileModel> {
    return this.getUserProfileById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserProfileModel>): UserProfileModel => r.body)
    );
  }

}
