/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TransportModel } from '../../models/transport-model';

export interface GetTransportsByCarrier$Params {
  carrierId?: string;
}

export function getTransportsByCarrier(http: HttpClient, rootUrl: string, params?: GetTransportsByCarrier$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TransportModel>>> {
  const rb = new RequestBuilder(rootUrl, getTransportsByCarrier.PATH, 'get');
  if (params) {
    rb.query('carrierId', params.carrierId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TransportModel>>;
    })
  );
}

getTransportsByCarrier.PATH = '/api/transports/get-all-by-carrier';
