/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OfferStatus } from '../models/offer-status';
export interface OfferModel {
  carrierId?: string;
  id?: string;
  orderId?: string;
  status?: OfferStatus;
}
