/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum OfferStatus {
  Unknown = 'Unknown',
  Pending = 'Pending',
  Accepted = 'Accepted',
  Rejected = 'Rejected'
}
