/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransportType } from '../models/transport-type';
export interface TransportModel {
  capacity?: number;
  carrierId?: string;
  id?: string;
  licensePlate?: string | null;
  type?: TransportType;
}
