/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfileInfo {
  address?: string | null;
  birthDate?: string;
  email?: string | null;
  firstName?: string | null;
  id?: string;
  lastName?: string | null;
  phoneNumber?: string | null;
  profilePicture?: string | null;
}
